import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import "./globals.css";
import { cn } from "@/lib/utils";
import GridPattern from "@/components/magicui/grid-pattern";
import { TooltipProvider } from "@/components/ui/tooltip"
export const metadata: Metadata = {
  title: "Ai-Twitter Bio Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(GeistSans.variable, "font-sans")}>
      <GridPattern className="-z-10 opacity-70" width={60} height={60} />
      <TooltipProvider>
        {children}
      </TooltipProvider>
      </body>
    </html>
  );
}
